[project]
name = "embbeded-software-testing"
version = "0.1.0"
description = ""
authors = [
    {name = "SurajPratapSharma",email = "surajsharma9085@yahoo.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "embbeded_software_testing", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
